const mascotPath = (category: string, name: string) => `/mascot/fox/${category}/${name}.png`

const names = (category: string, items: string[]) => items.map((item) => mascotPath(category, item))

export const mascotLibrary = {
  idle: names('idle', [
    'fox_calm',
    'fox_drink_hot_beverage',
    'fox_listen_music',
    'fox_peaceful_sleep',
    'fox_read_book',
    'fox_sit_nicely',
    'fox_sleep',
    'fox_sleep_on_moon',
    'fox_stand',
    'fox_yawn',
  ]),
  thinking: names('thinking', [
    'fox_build_blocks',
    'fox_check_tasks',
    'fox_detective',
    'fox_explore',
    'fox_get_idea',
    'fox_inspect',
    'fox_read_report',
    'fox_record_notes',
    'fox_study_at_desk',
    'fox_think',
    'fox_use_binoculars',
    'fox_write_notes',
  ]),
  tools: names('tools', [
    'fox_carry_files',
    'fox_complete_checklist',
    'fox_give_presentation',
    'fox_online_support',
    'fox_repair_hand_wrench',
    'fox_repair_large_wrench',
    'fox_use_computer',
  ]),
  success: names('status', [
    'fox_blow_kiss',
    'fox_blush',
    'fox_celebrate',
    'fox_cheer',
    'fox_clap',
    'fox_confident_hands_on_hips',
    'fox_confident_one_hand_on_hip',
    'fox_encourage',
    'fox_give_flowers',
    'fox_give_gift',
    'fox_give_love',
    'fox_happy_jump',
    'fox_hug_heart',
    'fox_laugh_to_tears',
    'fox_mail_love_letter',
    'fox_ok',
    'fox_party',
    'fox_proud',
    'fox_salute',
    'fox_sayhi',
    'fox_thank_you',
    'fox_thumbs_up',
    'fox_win_award',
  ]),
  error: names('status', [
    'fox_angry',
    'fox_angry_run',
    'fox_cry',
    'fox_dizzy',
    'fox_facepalm',
    'fox_gasp',
    'fox_nervous',
    'fox_shocked',
    'fox_surprised',
    'fox_worried',
  ]),
  waiting: names('status', [
    'fox_please',
    'fox_raise_hand',
    'fox_shy_bow',
  ]),
  fun: names('fun', [
    'fox_basketball',
    'fox_blow_bubbles',
    'fox_blow_dandelion',
    'fox_bowling',
    'fox_brush_teeth',
    'fox_build_sandcastle',
    'fox_cook',
    'fox_cycling',
    'fox_dance_with_headphones',
    'fox_eat_taiyaki',
    'fox_fishing',
    'fox_fly_kite',
    'fox_hold_umbrella',
    'fox_ice_skate',
    'fox_jump_rope',
    'fox_lift_dumbbell',
    'fox_magic_show',
    'fox_make_snowball',
    'fox_paint_canvas',
    'fox_paint_with_brush',
    'fox_plant_tree',
    'fox_play_ball',
    'fox_play_drums',
    'fox_play_games',
    'fox_play_guitar',
    'fox_ride_scooter',
    'fox_roast_marshmallow',
    'fox_shopping',
    'fox_side_stretch',
    'fox_sing',
    'fox_skateboard',
    'fox_ski_happily',
    'fox_skip_happily',
    'fox_sprint_sideways',
    'fox_sweep_floor',
    'fox_swim',
    'fox_taekwondo',
    'fox_take_photo',
    'fox_take_selfie',
    'fox_travel_with_luggage',
    'fox_water_plant',
    'fox_wave_magic_wand',
  ]),
} as const

export const idleMascots = [...mascotLibrary.idle, ...mascotLibrary.fun]
export const workingMascots = [...mascotLibrary.thinking, ...mascotLibrary.tools]

export function mascotAt(items: readonly string[], index: number, fallback: string) {
  return items.length > 0 ? items[Math.abs(index) % items.length] : fallback
}
